### PR TITLE
add ashgen.R (ash for general likelihood)

### PR DESCRIPTION
**Pull request by mengyin**
Add function ashgen() to deal with general likelihood (error distribution).

### CODE REVIEW

**Comment by stephens999** [comment]
i think we need to discuss/think about how to proceed. There is a lot of repetition of existing code here - and I can see why, but I'd like to try to avoid it if possible. I think it may take a bit of thought to see how best to proceed. It may require some refactoring of existing code to make things work nicely.

**Comment by stephens999** [comment]
I've started a new branch, general, where I have started refactoring the ashr code to make the general case tidier. Particularly I have replaced most/all of the mixture methods that took (betahat, sebetahat, df)
as parameter with just a single parameter "data". This makes things cleaner so that we don't need a different version of each function with different parameter names.

**Comment by pcarbo** [comment]
Should this pull request be deleted?

**Comment by stephens999** [comment]
i believe so as it is now defunct.
Matthew

**Pull request closed without merging**
