### PR TITLE
fundamental part of truncated normal cases.

### PR DESCRIPTION
**Pull request by MuzheZeng**
In ash, I only add the mixcompdist part, which is easy.

tnormalmix is just like normalmix, unimix, etc. All mathematics deductions are proved and checked.

truncnorm.R is modified with necessity. Though I solved the sd = 0 case last time, I did not consider situation when sd is a matrix. This modified version can take situations when sd is a vector and matrix into account and acquire the result without looping.

### CODE REVIEW

**Comment by stephens999** [comment]
your pull requests has conflicts with the current ash.R file.
can you pull the current version of ash, merge with your pull request, and
resend the pull request?

**Comment by stephens999** [comment]
@MuzheZeng this still has conflicts with the main branch that need resolving.

Given your previous issues, you might need to re-clone my main repo and putting in your changes afresh, and start a new pull request, rather than continuing this one. Generally it might be easiest if
each pull request is a small change.. that makes it easier to review.

**Comment by MuzheZeng** [comment]
ok sir！--------------------
Muzhe Zeng
University of Chicago, Master of Statistics
Peking University in School of Mathematics(Bachelor)
Double major in Economics, CCER Club(Bachelor)
            在2016年11月18日 23:47，stephens999 写道:@MuzheZeng this still has conflicts with the main branch that need resolving.

Given your previous issues, you might need to re-clone my main repo and putting in your changes afresh, and start a new pull request, rather than continuing this one. Generally it might be easiest if
each pull request is a small change.. that makes it easier to review.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stephens999/ashr","title":"stephens999/ashr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stephens999/ashr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stephens999 in #42: @MuzheZeng this still has conflicts with the main branch that need resolving.\r\n\r\nGiven your previous issues, you might need to re-clone my main repo and putting in your changes afresh, and start a new pull request, rather than continuing this one. Generally it might be easiest if\r\neach pull request is a small change.. that makes it easier to review.\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/stephens999/ashr/pull/42#issuecomment-261695469"}}}

**Comment by pcarbo** [comment]
Hi Muzhe,

I have some instructions for you to follow. The aim is to merge Matthew's recent changes *into your master branch.* In this way, you will be up-to-date with Matthew's changes, and then the merge from your fork to Matthew's repo will be more straightforward. 

Please complete these steps, and then once you are done, let's reconvene. 

*Note to Matthew:* This is potentially useful in other situations, although in this case things got more complicated than they should be, and the hope is to take steps to avoid this in the future.

Another note: For all these commands you can use the `--help` flag to learn about what they are doing, or `--qwerty` to get a quick summary of the options (the latter is a "trick" by choosing a nonsense flag). Alternatively look up a section in the [Git Pro book](https://git-scm.com/book/en/v2).

1. Clone your fork:

```bash
git clone https://github.com/MuzheZeng/ashr.git muzhezeng-ashr
git remote rename origin origin-muzhe
```

2. Add a "remote" for Matthew's repo and checkout his master branch:

```bash
git remote add origin-matthew https://github.com/stephens999/ashr.git
git remote -v
git fetch origin-matthew master
git branch -m master master-muzhe
git checkout -b master-matthew origin-matthew/master
git branch -a
``` 

3. Now that we have checked out both master branches, we can compare them, e.g., here are some pretty cool ways of doing this from the command line:

```bash
git show-branch --date-order --sha1-name master-matthew master-muzhe
git log --decorate --oneline --graph master-muzhe master-matthew
```

4. We are now ready to attempt the merge.

```bash
git checkout master-muzhe
git merge master-matthew
```

5. To summarize the merge, here are some useful commands:

```bash
git status -s
git diff --stat
git diff --cc R/ash.R
```

Let me know if you run into problems with any of these steps.

Once you have completed these steps, it is now your task to **resolve the conflicts** in the two R files. To find and understand the conflicts, your best friend is `git diff --cc`. Once you have modified the unmerged files to your satisfaction, let's sit down and figure out what are the next steps so that we can successfully complete the merge and push the updates back to github. Sounds good?

**Comment by stephens999** [comment]
There were still conflicts!! To try to help, I resolved these conflicts myself, and pushed them to the branch `MuzheZeng-master`. So this branch should now contain all your new work with
conflict resolved- please check this. If it looks good then you can work from this branch to
try to resolve the remaining problems.

The remaining problems are to do with my_etruncnorm
not returning a matrix correctly.

In some of your tests you had by-passed this problem by using "as.numeric" to change the "real" answer to a vector. But this isn't the right approach - you actually want the result to be a matrix and you want the test to test for that. So I have removed the as.numeric from the tests like this:

real = c(-100,-100,30)
  a=c(-Inf,-Inf,30)
  b=c(-100,-100,100)
  m=c(0,0,0)
  sd=c(1,0,0)
  expect_equal(real,my_etruncnorm(a,b,m,sd))
  real = matrix(real,3,4)
  m = matrix(m,3,4)
  sd = matrix(sd,3,4)
  expect_equal(real,my_etruncnorm(a,b,m,sd))
  a=c(0,0)
  b=c(1,2)
  m = rbind(c(0,2,4),c(0,0,0))
  sd = 0
  real = rbind(c(0,1,1),c(0,0,0))
  expect_equal(real,my_etruncnorm(a,b,m,sd))

**Pull request closed without merging**
